export const names = [
  "Madan Sharma",
  "Nick Tim",
  "Himanshu Singh",
  "Gaurav Kumar",
  "Abhishek Singh",
  "Manjeet Singh",
  "Raja Sagar",
  "Raghvan Kumar",
  "Neelaish Kumar",
  "Banty Baghel",
  "Mohit Thakur",
  "Carly Maith",
  "Dolly Singh",
  "Elly Paerl",
  "Froegn Josh",
  "Illi Kaith",
  "John Kumar",
  "Kartik Kumar",
  "Lakhan Baghel",
  "Oastry Martyrl",
  "Palak Sharma",
  "Rakesh Jha",
  "Sobhit Singh",
];
